<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the `super_admins` table (public schema only, KOZ-8). No tenant
 * schema ever gets this table — that is what makes a super admin
 * structurally invisible from within a tenant schema, not merely
 * access-controlled away from it.
 */
final class Version20260819160100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the super_admins table (public schema): tenant-independent admin accounts.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE super_admins (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_super_admins_email ON super_admins (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE super_admins');
    }
}
