<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Replaces the plain `roles` JSON column on `users` (KOZ-8) with a proper
 * roles-with-permissions model (KOZ-9), all in the public schema:
 *
 * - `permissions`: fine-grained permission names (e.g. `tenant:list`).
 * - `roles`: named roles (e.g. `ROLE_SUPER_ADMIN`).
 * - `role_permissions`: which permissions a role grants (many-to-many).
 * - `user_roles`: which roles a user has (many-to-many), replacing the old
 *   `users.roles` JSON column.
 *
 * Seeds exactly the permission set this ticket's DoD requires — no more,
 * no less: `tenant:list` and `tenant:create`, both granted to
 * ROLE_SUPER_ADMIN, matching what the admin tenant API actually does today
 * (App\Tenancy\Infrastructure\Controller\TenantAdminController). No
 * permissions are invented ahead of functionality that doesn't exist yet.
 *
 * Since KOZ-8 has not shipped and carries no production data, this drops
 * `users.roles` outright rather than migrating existing rows — any
 * super-admin account created before this migration needs to be recreated
 * via `bin/console super-admin:create` afterwards.
 */
final class Version20260819170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Introduce roles/permissions tables (public schema) and seed ROLE_SUPER_ADMIN with tenant:list/tenant:create.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'name VARCHAR(100) NOT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_permissions_name ON permissions (name)');

        $this->addSql(
            'CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'name VARCHAR(100) NOT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_roles_name ON roles (name)');

        $this->addSql(
            'CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, '
            . 'PRIMARY KEY (role_id, permission_id))'
        );
        $this->addSql('CREATE INDEX IDX_1FBA94E6D60322AC ON role_permissions (role_id)');
        $this->addSql('CREATE INDEX IDX_1FBA94E6FED90CCA ON role_permissions (permission_id)');
        $this->addSql(
            'ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_role '
            . 'FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
        $this->addSql(
            'ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_permission '
            . 'FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE'
        );

        $this->addSql(
            'CREATE TABLE user_roles (user_id INT NOT NULL, role_id INT NOT NULL, '
            . 'PRIMARY KEY (user_id, role_id))'
        );
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql(
            'ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user '
            . 'FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
        $this->addSql(
            'ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_role '
            . 'FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE'
        );

        $this->addSql('ALTER TABLE users DROP COLUMN roles');

        // Seed data: ROLE_SUPER_ADMIN with the two permissions the existing
        // super-admin API actually uses.
        $this->addSql("INSERT INTO roles (name) VALUES ('ROLE_SUPER_ADMIN')");
        $this->addSql("INSERT INTO permissions (name) VALUES ('tenant:list'), ('tenant:create')");
        $this->addSql(
            "INSERT INTO role_permissions (role_id, permission_id) "
            . "SELECT r.id, p.id FROM roles r, permissions p "
            . "WHERE r.name = 'ROLE_SUPER_ADMIN' AND p.name IN ('tenant:list', 'tenant:create')"
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql("ALTER TABLE users ADD COLUMN roles JSON NOT NULL DEFAULT '[]'");
        $this->addSql('DROP TABLE user_roles');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE permissions');
    }
}
