<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260819053803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the tenants table (public schema): subdomain -> tenant schema name mapping.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tenants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subdomain VARCHAR(63) NOT NULL, schema_name VARCHAR(63) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tenants_subdomain ON tenants (subdomain)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tenants_schema_name ON tenants (schema_name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE tenants');
    }
}
