<?php

declare(strict_types=1);

namespace App\Migrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the `tenant_users` and `tenant_user_api_tokens` tables inside a
 * tenant schema (KOZ-11): the first tenant-side authentication model in
 * this codebase, structurally isolated per tenant the same way
 * App\User\Domain\User (the public-schema-only super-admin account) is
 * structurally isolated from every tenant schema — neither table exists in
 * `public`, so a tenant user (and any token issued for one) is invisible
 * outside its own tenant schema, not merely access-controlled away from it.
 *
 * `roles` is a plain JSON array of role names for now, not the
 * Role/Permission entity model KOZ-9 introduced for App\User — deliberately
 * minimal first version (see the KOZ-11 ticket).
 *
 * `tenant_user_api_tokens` only ever stores the SHA-256 hash of an issued
 * bearer token, never the plaintext (see App\TenantUser\Domain\TenantApiToken).
 */
final class Version20260819180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create tenant_users and tenant_user_api_tokens tables (tenant schema, KOZ-11).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE tenant_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_tenant_users_email ON tenant_users (email)');

        $this->addSql(
            'CREATE TABLE tenant_user_api_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'tenant_user_id INT NOT NULL, token_hash VARCHAR(64) NOT NULL, '
            . 'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_tenant_user_api_tokens_token_hash ON tenant_user_api_tokens (token_hash)');
        $this->addSql('CREATE INDEX idx_tenant_user_api_tokens_tenant_user_id ON tenant_user_api_tokens (tenant_user_id)');
        $this->addSql(
            'ALTER TABLE tenant_user_api_tokens ADD CONSTRAINT fk_tenant_user_api_tokens_tenant_user '
            . 'FOREIGN KEY (tenant_user_id) REFERENCES tenant_users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE tenant_user_api_tokens');
        $this->addSql('DROP TABLE tenant_users');
    }
}
