<?php

declare(strict_types=1);

namespace App\Migrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Baseline tenant-schema migration (KOZ-7).
 *
 * This is the first migration in the *tenant* migration set — separate from
 * the *public* migration set under /migrations (see
 * config/packages/doctrine_migrations.yaml and App\Tenancy\Infrastructure\TenantSchemaMigrator).
 * It runs once per tenant schema, tracked by its own `doctrine_migration_versions`
 * table living inside that schema, rather than in `public`.
 *
 * It only creates a small marker table for now, proving the tenant
 * migration set runs independently of the public one end to end
 * (`tenant:provision`, `tenant:migrate --all`). Future tenant-schema tables
 * (orders, products, ...) are added as further migrations in this
 * directory/namespace.
 */
final class Version20260819060000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline tenant schema: creates the tenant_provisioning_marker table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE tenant_provisioning_marker '
            . '(id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provisioned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE tenant_provisioning_marker');
    }
}
