<?php

declare(strict_types=1);

namespace App\Migrations\Tenant;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Baseline tenant-schema migration: the first migration in the *tenant*
 * migration set, separate from the *public* set under /migrations. Runs
 * once per tenant schema, tracked by its own `doctrine_migration_versions`
 * table living inside that schema rather than in `public`. Only creates a
 * small marker table for now, proving the tenant migration set runs
 * independently of the public one end to end.
 */
final class Version20260819060000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline tenant schema: creates the tenant_provisioning_marker table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE tenant_provisioning_marker '
            . '(id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provisioned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE tenant_provisioning_marker');
    }
}
