#!/usr/bin/env bash
# Generate a per-worktree .env for docker-compose, based on a KOZ issue number.
#
# Usage:
#   scripts/setup-worktree-env.sh <issue-number>
#
# Example:
#   scripts/setup-worktree-env.sh 12
#
# This writes a .env file next to docker-compose.yml (in the repo/worktree
# root this script is called from) with:
#   COMPOSE_PROJECT_NAME=koz-<n>      -> namespaces container + volume names
#   FRONTEND_PORT=3000+<n>            -> frontend published port
#   BACKEND_PORT=8000+<n>             -> backend published port
#   DATABASE_PORT=5432+<n>            -> database published port
#   NEXT_PUBLIC_API_URL=http://localhost:<BACKEND_PORT>
#
# Run this once per worktree (e.g. right after creating a worktree for
# KOZ-<n>) before `make up`. Re-run it any time to regenerate the .env.

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <issue-number>" >&2
  echo "Example: $0 12   # sets up ports/names for KOZ-12" >&2
  exit 1
fi

N="$1"

if ! [[ "$N" =~ ^[0-9]+$ ]]; then
  echo "Error: issue number must be a positive integer, got '$N'" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

FRONTEND_PORT=$((3000 + N))
BACKEND_PORT=$((8000 + N))
DATABASE_PORT=$((5432 + N))

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-worktree-env.sh for KOZ-${N} — do not commit.
# Regenerate at any time with: scripts/setup-worktree-env.sh ${N}
COMPOSE_PROJECT_NAME=koz-${N}
FRONTEND_PORT=${FRONTEND_PORT}
BACKEND_PORT=${BACKEND_PORT}
DATABASE_PORT=${DATABASE_PORT}
NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
EOF

echo "Wrote ${ENV_FILE} for KOZ-${N}:"
echo "  COMPOSE_PROJECT_NAME=koz-${N}"
echo "  frontend -> http://localhost:${FRONTEND_PORT}"
echo "  backend  -> http://localhost:${BACKEND_PORT}"
echo "  database -> localhost:${DATABASE_PORT}"
echo ""
echo "Run 'make up' in this worktree to start the isolated stack."
