#!/usr/bin/env bash
# Generate a per-worktree .env for docker-compose, based on a KOZ issue number,
# and (KOZ-12) register that worktree's static Laravel Valet proxies.
#
# Usage:
#   scripts/setup-worktree-env.sh <issue-number>
#
# Example:
#   scripts/setup-worktree-env.sh 12
#
# This writes a .env file next to docker-compose.yml (in the repo/worktree
# root this script is called from) with:
#   COMPOSE_PROJECT_NAME=koz-<n>      -> namespaces container + volume names
#   FRONTEND_PORT=3000+<n>            -> frontend published port
#   BACKEND_PORT=8000+<n>             -> backend published port
#   DATABASE_PORT=5432+<n>            -> database published port
#   NEXT_PUBLIC_API_URL=http://localhost:<BACKEND_PORT>
#   APP_BASE_DOMAIN=kozijnr-koz-<n>.test
#
# and, if the `valet` CLI is available on this machine (see README.md "Local
# domains via Laravel Valet" for one-time `brew install valet && valet
# install && valet park` setup), registers this worktree's two static proxies:
#   api.kozijnr-koz-<n>.test   -> http://127.0.0.1:<BACKEND_PORT>
#   admin.kozijnr-koz-<n>.test -> http://127.0.0.1:<BACKEND_PORT>
# Per-tenant proxies (<tenant>.kozijnr-koz-<n>.test) are registered
# automatically and individually when a tenant is created in that worktree
# (App\Tenancy\Infrastructure\Valet\TenantValetProxyListener, dev-only) —
# not by this script, since no tenants exist yet at worktree-setup time.
#
# If `valet` isn't installed, the .env is still written normally and this
# script just skips proxy registration with a note — Valet is dev-only,
# optional local convenience on top of the port-based setup, never a hard
# requirement to run the stack.
#
# Run this once per worktree (e.g. right after creating a worktree for
# KOZ-<n>) before `make up`. Re-run it any time to regenerate the .env and
# re-register the proxies (`valet proxy` is idempotent — safe to repeat).

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <issue-number>" >&2
  echo "Example: $0 12   # sets up ports/names for KOZ-12" >&2
  exit 1
fi

N="$1"

# Reject leading zeros (e.g. "08", "012") outright rather than silently
# reinterpreting them: bash treats a leading-zero literal as octal in
# arithmetic contexts ($((...))), which would either misparse the number
# (e.g. "012" -> decimal 10, a silent port collision) or crash under
# set -e for invalid octal digits (e.g. "008"). Requiring a "clean" decimal
# integer here keeps the arithmetic below unambiguous.
if ! [[ "$N" =~ ^[1-9][0-9]*$ ]]; then
  echo "Error: issue number must be a positive integer without leading zeros, got '$N'" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

FRONTEND_PORT=$((3000 + N))
BACKEND_PORT=$((8000 + N))
DATABASE_PORT=$((5432 + N))
VALET_DOMAIN="kozijnr-koz-${N}.test"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-worktree-env.sh for KOZ-${N} — do not commit.
# Regenerate at any time with: scripts/setup-worktree-env.sh ${N}
COMPOSE_PROJECT_NAME=koz-${N}
FRONTEND_PORT=${FRONTEND_PORT}
BACKEND_PORT=${BACKEND_PORT}
DATABASE_PORT=${DATABASE_PORT}
NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
APP_BASE_DOMAIN=${VALET_DOMAIN}
EOF

echo "Wrote ${ENV_FILE} for KOZ-${N}:"
echo "  COMPOSE_PROJECT_NAME=koz-${N}"
echo "  frontend -> http://localhost:${FRONTEND_PORT}"
echo "  backend  -> http://localhost:${BACKEND_PORT}"
echo "  database -> localhost:${DATABASE_PORT}"
echo "  APP_BASE_DOMAIN=${VALET_DOMAIN}"
echo ""

if command -v valet >/dev/null 2>&1; then
  echo "Registering Valet proxies for ${VALET_DOMAIN}..."
  valet proxy "api.${VALET_DOMAIN}" "http://127.0.0.1:${BACKEND_PORT}" \
    || echo "  Warning: 'valet proxy api.${VALET_DOMAIN}' failed — register it manually if needed." >&2
  valet proxy "admin.${VALET_DOMAIN}" "http://127.0.0.1:${BACKEND_PORT}" \
    || echo "  Warning: 'valet proxy admin.${VALET_DOMAIN}' failed — register it manually if needed." >&2
  echo "  api.${VALET_DOMAIN}   -> http://127.0.0.1:${BACKEND_PORT}"
  echo "  admin.${VALET_DOMAIN} -> http://127.0.0.1:${BACKEND_PORT}"
  echo ""
  echo "Tenant subdomains (<tenant>.${VALET_DOMAIN}) are registered automatically"
  echo "when a tenant is created via 'make up' + tenant:provision in this worktree."
else
  echo "Note: 'valet' CLI not found — skipping automatic proxy registration."
  echo "  See README.md \"Local domains via Laravel Valet\" to install Valet, then"
  echo "  re-run this script (or run the 'valet proxy' commands above by hand) to"
  echo "  get api.${VALET_DOMAIN} / admin.${VALET_DOMAIN} working."
fi

echo ""
echo "Run 'make up' in this worktree to start the isolated stack."
