#!/usr/bin/env bash
# Generate the root .env docker-compose reads, for either the main checkout or
# a per-worktree environment based on a KOZ issue number.
#
# Usage:
#   scripts/setup-worktree-env.sh <issue-number>   # worktree for KOZ-<n>
#   scripts/setup-worktree-env.sh main             # the main checkout
#
# Writes .env next to docker-compose.yml (in the repo/worktree root this
# script lives in) with:
#   COMPOSE_PROJECT_NAME=koz-<n>  (or kozijnr)  -> namespaces containers,
#                                                  volumes and the proxy aliases
#   DATABASE_PORT=5432+<n>        (or 5432)     -> the only published port
#   APP_BASE_DOMAIN=koz-<n>.kozijnr.localhost (or kozijnr.localhost)
#
# All HTTP traffic goes through the shared nginx proxy (docker/proxy), which
# routes api.<base> / admin.<base> / <tenant>.<base> to this stack by
# hostname — no per-stack ports, no per-worktree proxy registration. See
# README.md "Local domains via nginx".
#
# `make up` runs this automatically when no .env exists yet (deriving <n>
# from a koz-<n> branch name, or "main" on the main branch). Re-run it any
# time to regenerate.

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <issue-number>|main" >&2
  echo "Example: $0 12   # sets up the isolated environment for KOZ-12" >&2
  exit 1
fi

N="$1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

if [ "$N" = "main" ]; then
  PROJECT="kozijnr"
  DATABASE_PORT=5432
  BASE_DOMAIN="kozijnr.localhost"
  LABEL="the main checkout"
else
  # Reject leading zeros (e.g. "08", "012") outright rather than silently
  # reinterpreting them: bash treats a leading-zero literal as octal in
  # arithmetic contexts, which would either misparse the number or crash
  # under set -e for invalid octal digits.
  if ! [[ "$N" =~ ^[1-9][0-9]*$ ]]; then
    echo "Error: issue number must be a positive integer without leading zeros (or 'main'), got '$N'" >&2
    exit 1
  fi
  PROJECT="koz-${N}"
  DATABASE_PORT=$((5432 + N))
  BASE_DOMAIN="koz-${N}.kozijnr.localhost"
  LABEL="KOZ-${N}"
fi

cat > "$ENV_FILE" <<EOT
# Generated by scripts/setup-worktree-env.sh for ${LABEL} — do not commit.
# Regenerate at any time with: scripts/setup-worktree-env.sh ${N}
COMPOSE_PROJECT_NAME=${PROJECT}
DATABASE_PORT=${DATABASE_PORT}
APP_BASE_DOMAIN=${BASE_DOMAIN}
EOT

echo "Wrote ${ENV_FILE} for ${LABEL}:"
echo "  COMPOSE_PROJECT_NAME=${PROJECT}"
echo "  database -> localhost:${DATABASE_PORT}"
echo "  API      -> http://api.${BASE_DOMAIN}"
echo "  admin    -> http://admin.${BASE_DOMAIN}"
echo "  tenants  -> http://<tenant>.${BASE_DOMAIN}"
echo ""
echo "Run 'make up' here to start the stack (the shared proxy is started along with it)."
